### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by zonca** [zonca/cmb-s4-data-portal#2]
Want to give access only to collaboration members, in the future partly public, partly for members.

This is probably just via globus, nothing to do with the portal.
Asked NERSC.

**Comment by zonca** [comment]
The globus endpoint currently is readable by anyone with a globus account, and it is administered by me and Ted.

## Same permissions for everyone

Use globus groups: https://docs.globus.org/how-to/managing-groups/
then I can set the endpoint so only members of this Globus group can transfer files.

We can also use SDK to invite users automatically in Python.

Need to rerun this once in a while to include updates to membership.

## Authenticate with SSO

It seems like it is an add-on to paid subscriptions, see https://www.globus.org/subscriptions:

> The alternate identity provider subscription enables you to add a new alternative identity provider to Globus, that may be used in lieu of currently-supported Globus mechanisms for authenticating your users. For example, if your campus uses a custom identity management system for single sign-on, you may integrate that system with Globus so that your users can log into Globus using their campus credentials. Globus supports InCommon identity providers via CILogon, a standard feature that is available at no additional cost. An alternate identity provider may only be added to a Standard subscription.

@jdborrill maybe someone familiar with the CMB-S4 SSO can look into this?

## Different permissions for members / public

Lisa suggested to use the data portal, but I don't see it supported by default, so it requires coding it.
Easier would be to have 2 data portals, one for public and one for members. They are just lightweight containers, no problem having 2 running on Spin.

**Comment by zonca** [comment]
## CILogon

if the CMB-S4 SSO is based on CILogon or supports CILogon, maybe we can ask Globus if we can have everyone coming in through that authentication system be included in the CMB-S4 group?

**Comment by jdanderson3** [comment]
CMB-S4 SSO is not based on CILogon.   It was in an early iteration, but we found a non-trivial number of members were from institutions not part of InCommon.

**Comment by zonca** [comment]
I created a group named "CMB-S4" on Globus. No special permissions yet, just testing.

I wrote a Python script that calls the Globus SDK, looks if there is a user with a specific email address, if so, it adds them to the group.

I ran this using the "Email Address" column (I can also run it for the "Login Address", it doesn't hurt if a user is member of a group with multiple identities). It is quick, I am processing 50 at a time.

Out of the ~350 members, I successfully added 46. Among which @jdborrill and @elidart (can you check you see the group membership inside Globus?)

* Should I run also for the "Login Address"?
* Should I restrict the portal just to this group and announce that in the data portal homepage?

**Comment by zonca** [comment]
Put the script on Github and wrote a little tutorial: https://zonca.dev/2021/09/globus-groups-python-sdk.html

**Comment by zonca** [comment]
> 
>     * Should I run also for the "Login Address"?

executed also with "Login Address", now the group members are 53.

Working on group permissions.

**Comment by jdborrill** [comment]
I think the "preferred email" addresses should be enough, but I guess
there's no harm.

J
